const data = {
    REJECT_DESIGNER: "❌ Dizaynerlikni rad etish",
    APPROVE_DESIGNER: "✅ Dizaynerlikni tasdiqlash",
    VIEW_PRODUCTS: "🛍 Mahsulotlarni ko'rish",
    MY_ORDER: "📦 Buyurtmalarim",
    ACTIVE_ORDERS: "📦 Faol buyurtmalar",
    CATEGORY: "📝 Kategoriya",
    GET_ALL_DESIGNERS: "📝 Barcha dizaynerlar",
    STATISTICS: "📊 Statistika",
    MAIN_SERVICES: "🛠 Xizmatlar",
    PROFILE: "👤 Profil",
    SETTINGS: "🔧 Sozlamalar",
    HELP: "❓ Yordam",
    BACK: "🔙 Orqaga",
    BACK_TO_HOME: "🔙 Orqaga",
    BACK_TO_PROFILE: "🔙 Orqaga",
    CANCEL: "❌ Bekor qilish",
    CONFIRM: "✅ Tasdiqlash",
    CONFIRMED: "✅ Tasdiqlangan",
    CANCELLED: "❌ Bekor qilindi",
    MY_PROFILE: "👤 Mening profilim",
    MY_DATA: "📝 Mening ma'lumotlarim",
    CATEGORY_LIST: "📝 Kategoriyalar ro'yxati",
    BACK_TO_CATEGORY: "🔙 Kategoriyaga qaytish",
    EDIT_PROFILE_DATA: "📝 Ma'lumotlarni tahrirlash",
    YES: "✅ Ha",
    NO: "❌ Yo'q",
    NEXT: "👉 Keyingi",
    PREVIOUS: "👈 Oldingi",
    CART: "🛒 Savatcha",
    SHOP: "🛍 Do'kon",
    ADD_TO_CART: "🛒 Savatchaga qo'shish",
    REGISTRATION: "📝 Ro'yxatdan o'tish",
    LOGIN: "🔑 Kirish",
    LOGOUT: "🔓 Chiqish",
    PAYMENT: "💳 To'lov",
    ORDER: "📦 Buyurtma berish",
    ORDER_CANCEL: "❌ Buyurtmani bekor qilish",
    CLEAR_CART: "🗑 Savatchani tozalash",
    MY_INCOME: "💰 Mening daromadim",
    ORDER_HISTORY: "📚 Buyurtmalar tarixi",
    DELETE: "🗑 O'chirish",
    EDIT: "📝 Tahrirlash",
    ADD: "➕ Qo'shish",
    ADD_CATEGORY: "➕ Qo'shish",
    EDIT_CATEGORY: "📝 Tahrirlash",
    REMOVE: "➖ Olib tashlash",
    MAIN: "🏠 Bosh sahifa",
    BACK_TO_SHOP: "🔙 Do'kon qaytish",
    SEARCH: "🔍 Izlash",
    REGISTER_NEW_DESIGN: "📝 Yangi dizayn qo'shish",
    REGISTER_NEW_PRODUCT: "📝 Yangi mahsulot ro'yxatdan o'tkazish",
    REGISTER_NEW_CATEGORY: "📝 Yangi kategoriya ro'yxatdan o'tkazish",
    REGISTER_NEW_BRAND: "📝 Yangi brend ro'yxatdan o'tkazish",
    BEING_DESIGNER: "📝 Dizayner bo'lish",
    BEING_DESIGNER_CONFIRM: "📝 Dizayner bo'lishni tasdiqlash",
    BEING_DESIGNER_CANCEL: "❌ Dizayner bo'lishni bekor qilish",
    BEING_DESIGNER_CONFIRMED: "✅ Dizayner bo'lish tasdiqlangan",
    BEING_DESIGNER_CANCELLED: "❌ Dizayner bo'lish bekor qilindi",
    BEING_DESIGNER_REQUEST: "📝 Dizaynerlik so'rovi",
    BEING_DESIGNER_REQUESTED: "📝 Dizaynerlik so'rovi yuborildi",
    BEING_DESIGNER_REQUEST_CONFIRM: "📝 Dizaynerlik so'rovi tasdiqlash",
    BEING_DESIGNER_REQUEST_CANCEL: "❌ Dizaynerlik so'rovi bekor qilish",
    BEING_DESIGNER_REQUEST_CONFIRMED: "✅ Dizaynerlik so'rovi tasdiqlangan",
    BEING_DESIGNER_REQUEST_CANCELLED: "❌ Dizaynerlik so'rovi bekor qilindi",
};

module.exports = data;